name: Build macOS EXE

on:
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt pyinstaller

      - name: Build macOS executable
        run: |
          pyinstaller --onefile \
            --add-data "Home_Page.py:." \
            --add-data "pages:pages" \
            --add-data ".streamlit:.streamlit" \
            --collect-all streamlit \
            --collect-all pandas \
            --collect-all ortools \
            --collect-all rapidfuzz \
            --collect-all openpyxl \
            launcher.py
        shell: bash

      - name: Upload macOS EXE
        uses: actions/upload-artifact@v4
        with:
          name: macos-exe
          path: dist/launcher
